infinite-jest-server/config/routes.rb
InfiniteJest::Application.routes.draw do
  resources :applicants

  get "home/index"
  root :to => "home#index"

end

infinite-jest-server/app/models/applicant.rb
class Applicant < ActiveRecord::Base
  attr_accessible :age, :claimDate, :firstname, :lastname
  
  validates :firstname, :lastname, :presence => true
  validates :age,  numericality: {:greater_than  => 18}
  
end

infinite-jest-server/app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  #modify these actions to redirect to post
  
  
  # GET /applicants
  # GET /applicants.json
  def index
    @applicants = Applicant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @applicants }
    end
  end

  # GET /applicants/1
  # GET /applicants/1.json
  def show
    @applicant = Applicant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @applicant }
    end
  end

  # GET /applicants/new
  # GET /applicants/new.json
  def new
    @applicant = Applicant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @applicant }
    end
  end

  # GET /applicants/1/edit
  def edit
    @applicant = Applicant.find(params[:id])
  end

  # POST /applicants
  # POST /applicants.json
  def create
    @applicant = Applicant.new(params[:applicant])

    respond_to do |format|
      if @applicant.save
        format.html { redirect_to @applicant, notice: 'Applicant was successfully created.' }
        format.json { render json: @applicant, status: :created, location: @applicant }
      else
        format.html { render action: "new" }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /applicants/1
  # PUT /applicants/1.json
  def update
    @applicant = Applicant.find(params[:id])

    p @applicant

    respond_to do |format|
      if @applicant.update_attributes(params[:applicant])
        format.html { redirect_to @applicant, notice: 'Applicant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applicants/1
  # DELETE /applicants/1.json
  def destroy
    @applicant = Applicant.find(params[:id])
    @applicant.destroy

    respond_to do |format|
      format.html { redirect_to applicants_url }
      format.json { head :no_content }
    end
  end
end

infinite-jest-server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery
end

infinite-jest-server/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

infinite-jest-server/app/helpers/applicants_helper.rb
module ApplicantsHelper
end

infinite-jest-server/app/helpers/application_helper.rb
module ApplicationHelper
end

infinite-jest-server/app/helpers/home_helper.rb
module HomeHelper
end

infinite-jest-server/app/views/applicants/edit.html.erb
<h1>Editing applicant</h1>

<%= render 'form' %>

<%= link_to 'Show', @applicant %> |
<%= link_to 'Back', applicants_path %>

infinite-jest-server/app/views/applicants/index.html.erb
<h1>Listing applicants</h1>

<table>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Age</th>
    <th>Claimdate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @applicants.each do |applicant| %>
  <tr>
    <td><%= applicant.firstname %></td>
    <td><%= applicant.lastname %></td>
    <td><%= applicant.age %></td>
    <td><%= applicant.claimDate %></td>
    <td><%= link_to 'Show', applicant %></td>
    <td><%= link_to 'Edit', edit_applicant_path(applicant) %></td>
    <td><%= link_to 'Destroy', applicant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Applicant', new_applicant_path %>

infinite-jest-server/app/views/applicants/new.html.erb
<h1>New applicant</h1>

<%= render 'form' %>

<%= link_to 'Back', applicants_path %>

infinite-jest-server/app/views/applicants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Firstname:</b>
  <%= @applicant.firstname %>
</p>

<p>
  <b>Lastname:</b>
  <%= @applicant.lastname %>
</p>

<p>
  <b>Age:</b>
  <%= @applicant.age %>
</p>

<p>
  <b>Claimdate:</b>
  <%= @applicant.claimDate %>
</p>


<%= link_to 'Edit', edit_applicant_path(@applicant) %> |
<%= link_to 'Back', applicants_path %>

infinite-jest-server/app/views/home/index.html.erb
<h1>Server</h1>
<%= link_to "My Applicants", applicants_path %>

infinite-jest-server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Server</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>